import { useGraphql } from '../../utils/usegraphql'

export default defineEventHandler(async (event) => {
  const id = getQuery(event).id;
  const reqQuery = `query {
    articles(filters:{
        tags:{
          id:{
           eq:${id}
          } 
        }
      }){
      data{
        id,
        attributes{
          tittle,
          content,
          createdAt,
          good,
          discuss,
          see,
          summary,
          tags{
            data{
              attributes{
                tittle
              }
            }
          },
          author{
            data{
              attributes{
                name,
                discuss,
                level{
                  data{
                    attributes{
                      url
                    }
                  }
                },
                badge{
                  data{
                    attributes{
                      url
                    }
                  }
                },
                headImg{
                  data{
                    attributes{
                      url
                    }
                  }
                }
              }
            }
          },
          img{
            data{
              attributes{
                url
              }
            }
          }
        }
      }
    }
  }`
  return (await useGraphql(reqQuery)).articles;
})